name: External Repo Scheduler

on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  get-release-version:
    name: Get Release Version
    runs-on: ubuntu-latest
    outputs:
      is_update: ${{ steps.check_version.outputs.is_update }}
      result: ${{ steps.check_version.outputs.result }}
      docker_tags: ${{ steps.check_version.outputs.docker_tags }}
    steps:
      - uses: mogeko/latest-version@v1.1.2
        id: check_version
        with:
          repo: kovidgoyal/calibre
  print-release-version:
    name: Print Release Version
    runs-on: ubuntu-latest
    needs: get-release-version
    outputs:
      calibre-release-version: ${{ steps.output-release-info.outputs.CALIBRE_RELEASE_VERSION }}
      force-enable-docker-tags: ${{ steps.output-docker-tags.outputs.DOCKER_TAGS }}
    steps:
      - id: get-release-info
        run: |
          echo '${{ needs.get-release-version.outputs.is_update }}'
          echo '${{ needs.get-release-version.outputs.result }}' | jq '.'
          echo '${{ needs.get-release-version.outputs.docker_tags }}'
          echo '${{ needs.get-release-version.outputs.result }}' | jq -r '.stable_version'
      - id: output-release-info
        run: echo "CALIBRE_RELEASE_VERSION=$(echo '${{ needs.get-release-version.outputs.result }}' | jq -r '.stable_version')" >> $GITHUB_OUTPUT
      - id: output-docker-tags
        run: echo "DOCKER_TAGS=$(echo '${{ needs.get-release-version.outputs.docker_tags }}' | sed 's/enable=false/enable=true/g')" >> $GITHUB_OUTPUT
  call-package-workflow:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ryanheyser/docker-calibre/.github/workflows/package.yaml@ryanheyser-main
    needs: [get-release-version,print-release-version]
    # if: needs.get-release-version.outputs.is_update == 'true'
    with:
      calibre-version: ${{ needs.print-release-version.outputs.calibre-release-version }}
      additional-docker-tags: ${{ github.event_name == 'workflow_dispatch' && needs.get-release-version.outputs.force-enable-docker-tags || needs.get-release-version.outputs.docker_tags }}
    secrets: inherit
